# fly.toml app configuration file generated for nutech-api on 2024-11-23T00:42:48+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nutech-api'
primary_region = 'sin'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 4444
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
